version: '3'
services:
  php:
    build: ./php-fpm
    volumes:
      - ./webapp:/var/www/webapp
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    container_name: webapp
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/webapp
      - ./nginx/webapp.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    depends_on:
      - php
  mysql:
    build:
      context: docker-entrypoint-initdb.d
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dbsql
    ports:
      - "3306:3306"
  mysql-test:
    build:
      context: docker-entrypoint-initdb.d
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dbsql-test
    ports:
      - "3308:3306"